name: nannyacademy
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intl: ^0.17.0
  flutter_rounded_date_picker: 1.0.0
  http:
  image_picker: ^0.6.5+3
  shared_preferences: ^0.5.7
  expansion_tile_card:
  flutter_spinkit: ^5.1.0
  sqflite:
  localstorage:
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.5
  intl_phone_number_input: ^0.7.0+2
  csc_picker: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/lora.ttf